[package]
name = "confit"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
thiserror = "2.0.9"
in-place = "0.2.1"
detect-newline-style = "0.1.2"

[dev-dependencies]
tempfile = "3.14.0"